---
name: bosh-newrelic-infrastructure
releases:
- name: bosh-newrelic-infrastructure
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 15000-300000
  update_watch_time: 15000-300000

instance_groups:
- name: newrelic
  azs:
  - z1
  instances: 1
  jobs:
  - name: bosh-newrelic-infrastructure
    release: bosh-newrelic-infrastructure
  vm_type: default
  vm_extensions: [internet-required]
  persistent_disk_pool: 100GB
  stemcell: default
  networks:
  - name: default
  properties:
    newrelic_infra:
      license_key: ((newrelic_infra_license_key))
